name: frontend_CI
on:
  push:
    paths:
      - 'Frontend/**'
      - '.github/workflows/**'
jobs:
  test:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            Frontend

      - name: node_install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: install_deps
        run: npm ci
        working-directory: Frontend

      - name: test
        run: npm run test
        working-directory: Frontend

  build:
    runs-on:
      ubuntu-latest
    needs: test
    steps:
      - name: checkout_repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            Frontend

      - name: node_install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: install_deps
        run: npm ci
        working-directory: Frontend

      - name: build
        run: npm run build
        working-directory: Frontend
